### ISSUE TITLE
Openweathermap.org requires API key

### ISSUE THREAD

**Issue by tannerb** [oh-my-fish/plugin-weather#6]
Opening this for reference. Is this new, or am I missing something? After registering and adding my API key to the call everything is working as expected.

**Comment by sagebind** [comment]
This is definitely new; I was just using this two days ago and worked fine. In fact, I chose openweathermap.org because it _didn't_ need an API key. Apparently they changed this. I can work on a fix ASAP.

Choices are:
- Find a different service that doesn't need an API key
- Use one API key for the entire project
- Make every user sign up for an API key

The last option is a nasty one that I'd like to avoid.

**Comment by tannerb** [comment]
The free tier gives: 60 requests / minute, 50 000 per day. I think going with one API key is a safe bet at this point in time ;)

**Comment by sagebind** [comment]
I just sent them a message asking if this is OK per their terms of use.

**Comment by sagebind** [comment]
Their reply:

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/coderstephen">@coderstephen</a> It is. Please do let us know (via a ticket) of your app and APPID - we will mark it as used in free software.</p>&mdash; OpenWeatherMap (@OpenWeatherMap) <a href="https://twitter.com/OpenWeatherMap/status/653942563959771136">October 13, 2015</a></blockquote>

Looks like the all-clear. I'll set up a public API key and get a patch for the package ASAP. Thanks for letting me know about the issue.

**Comment by sagebind** [comment]
Updated -- the command should work again. Closing the issue.
